       PARAMETER(NDEmax=20000,NELmax=20000)
       PARAMETER(NDIM=NDEmax*Ndf)
       PARAMETER(NZMAX=3000000,
     .           NZLMAX=4000000,NZUMAX=6000000)
       PARAMETER(MatMax=10, MaxProp=25,MaxCon=100)
       PARAMETER(MaxEig=100)
       PARAMETER(NvfP=100)

C MatMax - maximum number of materials
C MaxProp - maximum number of material properties - E,ni,ro ... 
C MaxCon - maximum number of nodes  connected to a node
C NvfP   - maximum number of volume forces




